# -*- coding: utf-8 -*-
"""shopping_trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tw_Nv00Zt6LRkWoBcFKPfN43q2t2vaWv

##Importing Necessary Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

data =  pd.read_csv('/content/shopping_trends.csv')

"""##data exploration"""

data.head(5)

data.shape

data.info()

# check Missing value
data.isna().sum()

# Check Duplication
data.duplicated().sum()

# Check the number of unique values of each column
data.nunique()

# Check statistic of dataset
data.describe()

"""##Let's start checking the unique values for each column"""

for col in data.columns:
    print(f'Category in {col} is :\n {data[col].unique()}\n')
    print('\\'*50)

"""##Analysis📝 & Visualiation📊"""

# Drop Column Customer ID because it is not important in the analysis
data=data.drop(['Customer ID'],axis=1)

data.Age.describe()

# Assuming 'data' is your DataFrame with an 'Age' column
fig, ax = plt.subplots(figsize=(20, 8))

# Histogram (set density=True to match with KDE)
ax.hist(data['Age'], bins=20, edgecolor='black', alpha=0.7, color="#89CFF0", density=True)

# KDE (density curve)
data['Age'].plot(kind='kde', color="#FF69B4", linewidth=2, ax=ax)

# Labels and title
ax.set_xlabel('Age', fontsize=15)
ax.set_ylabel('Density', fontsize=15)
ax.set_title('Age Distribution Histogram with Density Curve', fontsize=20)
ax.legend(['Density Curve', 'Histogram'])

plt.tight_layout()
plt.show()

gender = data.Gender.value_counts()
print(gender,'\n')

plt.pie(gender,labels=gender.index,colors=["#89CFF0", "#FF69B4"],autopct='%.0f%%',explode=(0,0.1))
plt.legend(labels = gender.index, loc = "best")
plt.title('Gender')
plt.show()

data['Item Purchased'].value_counts()

plt.subplots(figsize=(20,8), dpi=100)
sns.countplot(data= data, x='Item Purchased',palette='cool')
plt.title("Item Purchased",fontsize=20)
plt.show()

CountOfCategory = data['Category'].value_counts()
CountOfCategory

plt.figure(figsize=(8,8))
plt.pie(CountOfCategory,labels=CountOfCategory.index,autopct='%0.0f%%',explode=(0,0,0,0.1))
plt.legend(CountOfCategory.index,loc =1)
plt.show()

data['Purchase Amount (USD)'].describe()

data['Location'].value_counts()

top_10_Location = data.Location.value_counts().sort_values(ascending=False)[:10]
plt.figure(figsize=(10, 8))
sns.barplot(x=top_10_Location, y=top_10_Location.index,palette='cool',linewidth = 4)
plt.title('Top10 The Most Location where the purchase was made',loc='center',fontweight='bold',fontsize=12)
plt.xlabel('Frequency',fontsize=15)
plt.ylabel('Location',fontsize=15)
plt.tight_layout()
plt.show()

size_count = data['Size'].value_counts()
size_count

plt.figure(figsize=(8,8))
plt.pie(size_count,labels=['M','L','S','XL'],autopct='%0.0f%%',explode=(0,0,0,0.1))
plt.legend( ['M','L','S','XL'],loc =1)
plt.title('Size of the purchased item')
plt.show()

data['Color'].value_counts()

Color = data['Color'].value_counts().sort_values(ascending=False)
plt.figure(figsize=(10, 8))
sns.barplot(x=Color, y=Color.index,palette='cool',linewidth = 4)
plt.title('The Colors which the purchase was made',loc='center',fontweight='bold',fontsize=12)
plt.xlabel('Count',fontsize=15)
plt.ylabel('Color',fontsize=15)
plt.tight_layout()
plt.show()

season = data['Season'].value_counts()
season

plt.figure(figsize=(8,8))
plt.pie(season,labels=['Spring','Fall','Winter','Summer'],autopct='%0.0f%%')
plt.legend( ['Spring','Fall','Winter','Summer'],loc =1)
plt.title('Season')
plt.show()

data['Review Rating'].describe()

count = data['Subscription Status'].value_counts()
count

plt.figure(figsize=(5,5))
plt.pie(count,labels=['No','Yes'],colors=["#89CFF0", "#FF69B4"],autopct='%0.0f%%',explode=(0,0.05))
plt.legend( ['No','Yes'],loc =1)
plt.title('Subscription Status')
plt.show()

Shipping_Type = data['Shipping Type'].value_counts()
Shipping_Type

plt.figure(figsize=(8, 5))
sns.barplot(x=Shipping_Type.index,y=Shipping_Type, palette='cool',linewidth = 5)
plt.title('Type of shipping chosen by the customer\n',loc='center',fontweight='bold',fontsize=12)
plt.xlabel('\n Shipping Type',fontsize=10)
plt.ylabel('Count \n',fontsize=10)
plt.tight_layout()
plt.show()

Discount_Applied =data['Discount Applied'].value_counts()
print(Discount_Applied)
plt.figure(figsize=(5,5))
plt.pie(Discount_Applied,labels=['No','Yes'],colors=["#89CFF0", "#FF69B4"],autopct='%0.0f%%',explode=(0,0.05))
plt.legend( ['No','Yes'],loc =1)
plt.title('Discount Applied')
plt.show()

Promo_Code_Used =data['Promo Code Used'].value_counts()
print(Promo_Code_Used)
plt.figure(figsize=(5,5))
plt.pie(Promo_Code_Used,labels=['No','Yes'],colors=["#89CFF0", "#FF69B4"],autopct='%0.0f%%',explode=(0,0.05))
plt.legend( ['No','Yes'],loc =1)
plt.title('Promo Code Used')
plt.show()

Payment_Method = data['Payment Method'].value_counts()
Payment_Method

plt.figure(figsize=(8, 5))
sns.barplot(x=Payment_Method.index,y=Payment_Method, palette='cool',linewidth = 5)
plt.title('Customer''s most preferred payment method',loc='center',fontweight='bold',fontsize=12)
plt.xlabel('Payment Method',fontsize=10)
plt.ylabel('Count',fontsize=10)
plt.tight_layout()
plt.show()

Frequency_of_Purchases =data['Frequency of Purchases'].value_counts()
print(Frequency_of_Purchases)
plt.figure(figsize=(10,10))
plt.pie(Frequency_of_Purchases,labels=Frequency_of_Purchases.index,autopct='%0.0f%%')
plt.legend( Frequency_of_Purchases.index,loc =1)
plt.title('Frequency of Purchases')
plt.show()

# Total number of plots = number of columns
num_plots = len(df.columns)

fig, axes = plt.subplots(nrows=num_plots, ncols=1, figsize=(10, 5 * num_plots))

# If there's only one column, axes may not be iterable
if num_plots == 1:
    axes = [axes]

for idx, col in enumerate(df.columns):
    print(pd.crosstab(data['Gender'], data[col]).T, '\n' + '#' * 50)
    sns.countplot(data=data, hue='Gender', x=col, palette=["#89CFF0", "#FF69B4"], ax=axes[idx])
    axes[idx].set_title(f"Countplot of {col} by Gender")
    axes[idx].set_ylabel('')
    axes[idx].spines['top'].set_visible(False)

plt.tight_layout()
plt.show()

pd.crosstab(data['Gender'], data['Category'], values=data['Age'],aggfunc=np.average)

data.groupby('Gender')['Purchase Amount (USD)'].sum()

data.groupby('Gender')['Purchase Amount (USD)'].sum().plot(kind='bar',figsize=(5,5),colormap='cool',ylabel='Purchase Amount (USD)')

pd.crosstab(data['Category'],data['Item Purchased']).T

pd.crosstab(data['Category'],data['Item Purchased']).plot(kind='bar',figsize=(20,8))

data.groupby(['Gender','Category'])['Purchase Amount (USD)'].sum()

data.groupby(['Gender','Category'])['Purchase Amount (USD)'].sum().plot(kind='bar',colormap='cool',ylabel='Purchase Amount (USD)')

data.groupby(['Category','Item Purchased'])['Purchase Amount (USD)'].sum()

data.groupby(['Category','Item Purchased'])['Purchase Amount (USD)'].sum().plot(kind='bar',colormap='cool',figsize=(15,5),ylabel='Purchase Amount (USD)')

pd.crosstab(data['Season'],data['Category'])

pd.crosstab(data['Season'],data['Category']).plot(kind='bar',figsize=(12,6),ylabel='Count')

pd.crosstab(data['Season'],data['Item Purchased']).T

pd.crosstab(data['Item Purchased'],data['Season']).plot(kind='bar',figsize=(18,10),ylabel='Count')

pd.crosstab(data['Season'],data['Category'],values=data['Purchase Amount (USD)'],aggfunc=np.sum)

pd.crosstab(data['Season'],data['Category'],values=data['Purchase Amount (USD)'],aggfunc=np.sum).plot(kind='bar',figsize=(12,6),ylabel='Purchase Amount (USD)')

pd.crosstab(data['Season'],data['Purchase Amount (USD)'].sum())

plt.figure(figsize=(15, 6))
sns.kdeplot(data= data, x='Purchase Amount (USD)',hue='Season',fill=True)
plt.title('Purchase Amount by Season')

data[data['Category'] == 'Clothing'].groupby('Size')['Purchase Amount (USD)'].sum()

data1 = pd.read_csv('/content/shopping_trends_updated.csv')

data1[(data1['Subscription Status'] == 'Yes') & (data1['Promo Code Used'] == 'Yes')]['Customer ID'].count()

data1[data1['Previous Purchases'] > 40]['Customer ID'].count()

data[(data['Gender'] == 'Female') & (data['Review Rating'] >= 3)]['Category'].mode()[0]

n_cols = 2
n_rows = (len(df.columns) + 1) // n_cols

fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, 5 * n_rows))
axes = axes.flatten()

for idx, col in enumerate(df.columns):
    sns.countplot(data=data, x=col, hue='Gender', palette=["#89CFF0", "#FF69B4"], ax=axes[idx])
    axes[idx].set_title(f"{col} Distribution by Gender", fontsize=14)
    axes[idx].set_ylabel('')
    axes[idx].spines['top'].set_visible(False)
    axes[idx].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

print(f"🔍 Insight: In {col}, Female customers tend to prefer ... while Male customers lean toward ...")

numeric_data = data.select_dtypes(include=np.number)
sns.heatmap(numeric_data.corr(), annot=True, cmap='coolwarm')
plt.title("Feature Correlation Matrix")
plt.show()

"""Visualize All Categorical Features by Gender in a Grid"""

